spring:
  datasource:
    url: jdbc:postgresql://ragchatbot.cvs2uesqwf7d.ap-south-1.rds.amazonaws.com:5432/jwt_security
    username: root
    password: awadh123##
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
  data:
    redis:
      host: ${SPRING_REDIS_HOST:localhost}
      port: ${SPRING_REDIS_PORT:6379}
